name: se501_plantheon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  table_calendar: ^3.0.9
  styled_divider: ^1.0.5
  image_picker: ^1.2.0
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter_screenutil: ^5.7.0+2
  flutter_html: ^3.0.0-beta.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  intl: ^0.20.2
  geolocator: ^13.0.1
  share_plus: ^10.1.2
  flutter_markdown: ^0.6.18
  supabase_flutter: ^2.5.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  carousel_slider: ^5.1.1
  toastification: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  cached_network_image : ^3.4.1
  dotted_line: ^3.2.3
  app_links: ^6.4.1
  flutter_tts: ^4.2.3
  rive: ^0.13.0
  lottie: ^3.1.2
  skeletonizer: ^2.1.1
  url_launcher: ^6.1.7
  jwt_decode: ^0.3.1
  pin_code_fields: ^8.0.1
  rename: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/animations/
    - .env
