name: se501_plantheon
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  table_calendar: ^3.0.9
  styled_divider: ^1.0.5
  image_picker: ^1.2.0
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter_screenutil:
  flutter_html: ^3.0.0-beta.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  intl: ^0.20.2
  geolocator: ^13.0.1
  share_plus: ^10.1.2
  flutter_markdown: ^0.6.18
  supabase_flutter: ^2.5.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  carousel_slider: ^5.1.1
  toastification: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/gif/
    - .env
